var fs = require("fs");
var xxtea = require("./xxtea.js");

function test1(e) {
    var key = Buffer.from("xteaKeyValue0123456789ABCDEF");
    if (e) { //encrypt
        var path_plain = "./plain.bin";
        var bytes = fs.readFileSync(path_plain);
        console.log("original bytes:" + bytes.length + " key:" + key.length);
        try {
            bytes = xxtea.encrypt(bytes, key);
            var path_e = "./e.out";
            fs.writeFileSync(path_e, bytes);
        } catch (e) {
            console.log("158", e);
        }
    } else { //decrypt
        var path_e = "./plain.bin.e"; //generated by other implementation
        var bytes = fs.readFileSync(path_e);
        console.log("original bytes:" + bytes.length + " key:" + key.length);
        try {
            bytes = xxtea.decrypt(bytes, key);
            var path_plain = "./p.out";
            fs.writeFileSync(path_plain, bytes);
        } catch (e) {
            console.log("182", e);
        }
    }
}

function test2() {
    var key = Buffer.from("xteaKey"); //  Value0123456789ABCDEF
    //encrypt
    var path_plain = "./plain.bin";
    var bytes = fs.readFileSync(path_plain);
    console.log("original bytes:" + bytes.length + " key:" + key.length);
    try {
        bytes = xxtea.encrypt(bytes, key);
        var path_e = "./e.out";
        fs.writeFileSync(path_e, bytes);
    } catch (e) {
        console.log("158", e);
    }
    //decrypt
    var path_e = "./e.out"; // "./plain.bin.e";
    var bytes = fs.readFileSync(path_e);
    console.log("original bytes:" + bytes.length + " key:" + key.length);
    try {
        bytes = xxtea.decrypt(bytes, key);
        var path_plain = "./p.out";
        fs.writeFileSync(path_plain, bytes);
    } catch (e) {
        console.log("182", e);
    }
}

test1(true);
test1(false);
// test2();
